#!/usr/bin/env bash
# Instalador de Grupos de aplicaciones para Plank Reloaded.
# Doble clic en «Instalar grupos de Plank» o:  ./install.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=i18n.sh
. "$ROOT/i18n.sh"
LOG="/tmp/plank-group-install-${USER:-user}.log"
ESTADO="${XDG_DATA_HOME:-$HOME/.local/share}/plank-group-docklet/instalacion.txt"
GRUPOS_DIR="${APLICACIONES_DOCK:-$HOME/Aplicaciones-dock}"
TITULO="$(pg title_install)"
GUI=0

# --- parte que corre con la contraseña del administrador ---
if [[ "${1:-}" == "--instalar-paquetes" ]]; then
  export DEBIAN_FRONTEND=noninteractive
  shift
  # Un repositorio de terceros roto no debe impedir instalar paquetes de Ubuntu/Mint.
  if ! apt-get install -y "$@"; then
    apt-get update || true
    apt-get install -y "$@"
  fi
  exit 0
fi

if [[ "${1:-}" == "--instalar-modulo" ]]; then
  meson install -C "${2:-$ROOT}/build"
  exit 0
fi

if [[ "${1:-}" == "--quitar-modulo" ]]; then
  so="${2:-}"
  if [[ -n "$so" && -f "$so" ]]; then
    rm -f "$so"
  fi
  exit 0
fi

: >"$LOG"

log() {
  printf '%s\n' "$*" >>"$LOG"
  printf '%s\n' "$*"
}

tiene_pantalla() {
  [[ -n "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ]]
}

usar_zenity() {
  tiene_pantalla && command -v zenity >/dev/null 2>&1
}

abrir_en_terminal() {
  local cmd="bash '$ROOT/install.sh'; echo; read -r -p '$(pg press_enter) '"
  local term
  for term in x-terminal-emulator gnome-terminal xfce4-terminal mate-terminal konsole lxterminal; do
    if command -v "$term" >/dev/null 2>&1; then
      if [[ "$term" == "gnome-terminal" ]]; then
        exec gnome-terminal -- bash -c "$cmd"
      fi
      exec "$term" -e "bash -c $(printf '%q' "$cmd")"
    fi
  done
  echo "$(pg open_terminal)" >&2
  exit 1
}

if usar_zenity; then
  GUI=1
elif tiene_pantalla && [[ ! -t 0 ]]; then
  abrir_en_terminal
fi

mensaje() {
  if [[ "$GUI" -eq 1 ]]; then
    zenity --info --title="$TITULO" --width=480 --text="$1" || true
  else
    printf '%b\n\n' "$1"
  fi
}

mensaje_error() {
  if [[ "$GUI" -eq 1 ]]; then
    zenity --error --title="$TITULO" --width=500 --text="$1" || true
  else
    printf '\nERROR: %b\n\n' "$1" >&2
  fi
}

preguntar() {
  if [[ "$GUI" -eq 1 ]]; then
    zenity --question --title="$TITULO" --width=480 --text="$1"
  else
    local respuesta=""
    printf '%b\n' "$1"
    read -r -p "$(pg continue_prompt)" respuesta || return 1
    [[ -z "$respuesta" || "$respuesta" =~ ^[sSyY] ]]
  fi
}

como_admin() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
    return
  fi
  if command -v pkexec >/dev/null 2>&1; then
    pkexec "$@"
  else
    sudo "$@"
  fi
}

paquete_instalado() {
  dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q "install ok installed"
}

paquetes_faltantes() {
  local paquete
  for paquete in \
    build-essential meson ninja-build valac pkg-config gettext \
    libgtk-3-dev libgee-0.8-dev; do
    if ! paquete_instalado "$paquete"; then
      printf '%s\n' "$paquete"
    fi
  done
  # plank-reloaded ya trae las cabeceras; libplank-dev es del Plank antiguo.
  if ! pkg-config --exists plank 2>/dev/null; then
    if apt-cache show libplank-dev >/dev/null 2>&1; then
      printf '%s\n' "libplank-dev"
    fi
  fi
  if command -v plank >/dev/null 2>&1; then
    return 0
  fi
  if apt-cache show plank-reloaded >/dev/null 2>&1; then
    printf '%s\n' "plank-reloaded"
  else
    printf '%s\n' "plank"
  fi
}

buscar_lanzador() {
  local nombre="$1"
  local carpeta
  for carpeta in \
    "$HOME/.local/share/applications" \
    /usr/share/applications \
    /usr/local/share/applications \
    /var/lib/flatpak/exports/share/applications \
    "$HOME/.local/share/flatpak/exports/share/applications" \
    /var/lib/snapd/desktop/applications; do
    if [[ -f "$carpeta/$nombre" ]]; then
      printf '%s\n' "$carpeta/$nombre"
      return 0
    fi
  done
  return 1
}

icono_grupo() {
  case "$1" in
    Desarrollo) printf '%s\n' "applications-development" ;;
    Web) printf '%s\n' "web-browser" ;;
    Comunicacion) printf '%s\n' "internet-chat" ;;
    *) printf '%s\n' "folder" ;;
  esac
}

rellenar_grupo() {
  local grupo="$1"
  shift
  local archivo origen
  mkdir -p "$GRUPOS_DIR/$grupo"
  for archivo in "$@"; do
    origen="$(buscar_lanzador "$archivo" || true)"
    if [[ -n "$origen" ]]; then
      ln -sfn "$origen" "$GRUPOS_DIR/$grupo/$archivo"
    fi
  done
}

escribir_dockitem() {
  local archivo="$1"
  local titulo="$2"
  local icono="$3"
  local carpeta="$4"
  cat >"$archivo" <<EOF
#This file auto-generated by Plank.
[PlankDockItemPreferences]
Launcher=docklet://app-group
SortBy=name
DirectoryStyle=0
ShowHiddenFiles=false
LargeIcons=false

[PlankGroupAppGroupPreferences]
Title=$titulo
GroupIcon=$icono
Folder=$carpeta
EOF
}

docks_activos() {
  if ! command -v python3 >/dev/null 2>&1; then
    printf '%s\n' "dock1"
    return
  fi
  python3 - <<'PY'
import ast, subprocess
try:
    raw = subprocess.check_output(
        ["gsettings", "get", "net.launchpad.plank", "enabled-docks"],
        text=True, stderr=subprocess.DEVNULL).strip()
except Exception:
    raw = ""
if raw in ("", "@as []"):
    print("dock1")
    raise SystemExit
try:
    items = ast.literal_eval(raw)
except Exception:
    print("dock1")
    raise SystemExit
for item in items or ["dock1"]:
    print(item)
PY
}

anadir_al_dock() {
  python3 - "$1" "$2" <<'PY'
import ast, subprocess, sys
dock, item = sys.argv[1], sys.argv[2]
path = f"/net/launchpad/plank/docks/{dock}/dock-items"
try:
    raw = subprocess.check_output(["dconf", "read", path], text=True).strip()
except Exception:
    raw = ""
if raw in ("", "@as []"):
    items = []
else:
    try:
        items = list(ast.literal_eval(raw))
    except Exception:
        items = []
if item not in items:
    items.append(item)
if items:
    value = "[" + ", ".join("'" + x.replace("'", "") + "'" for x in items) + "]"
else:
    value = "@as []"
subprocess.check_call(["dconf", "write", path, value])
PY
}

configurar_grupos() {
  mkdir -p "$GRUPOS_DIR"

  rellenar_grupo Desarrollo \
    code.desktop cursor.desktop org.gnome.Terminal.desktop \
    gnome-terminal.desktop org.x.editor.desktop geany.desktop \
    dbeaver-ce.desktop dbeaver-ue.desktop cmake-gui.desktop \
    org.gnome.Builder.desktop com.getpostman.Postman.desktop

  rellenar_grupo Web \
    firefox.desktop firefox-esr.desktop org.mozilla.firefox.desktop \
    brave-browser.desktop google-chrome.desktop chromium-browser.desktop \
    chromium.desktop opera.desktop vivaldi-stable.desktop microsoft-edge.desktop

  rellenar_grupo Comunicacion \
    telegramdesktop.desktop org.telegram.desktop.desktop discord.desktop \
    slack.desktop zoom.desktop thunderbird.desktop org.mozilla.Thunderbird.desktop \
    org.gnome.Evolution.desktop signal-desktop.desktop org.ferdium.Ferdium.desktop \
    com.github.IsmaelMartinez.teams_for_linux.desktop

  mkdir -p "$(dirname "$ESTADO")"
  {
    printf 'GRUPOS_DIR=%s\n' "$GRUPOS_DIR"
    printf 'DOCKLET=%s\n' "$(pkg-config --variable=libdir plank 2>/dev/null || echo /usr/lib)/plank/docklets/libdocklet-app-group.so"
  } >"$ESTADO"

  local dock launchers nombre titulo icono item
  for dock in $(docks_activos); do
    launchers="$HOME/.config/plank/$dock/launchers"
    mkdir -p "$launchers"
    for nombre in Desarrollo Web Comunicacion; do
      case "$nombre" in
        Desarrollo) titulo="$(pg group_dev)" ;;
        Web) titulo="$(pg group_web)" ;;
        Comunicacion) titulo="$(pg group_chat)" ;;
        *) titulo="$nombre" ;;
      esac
      icono="$(icono_grupo "$nombre")"
      item="app-group-${nombre,,}.dockitem"
      escribir_dockitem "$launchers/$item" "$titulo" "$icono" "$GRUPOS_DIR/$nombre"
      anadir_al_dock "$dock" "$item"
      printf 'DOCKITEM=%s/%s\n' "$launchers" "$item" >>"$ESTADO"
      printf 'DOCK=%s:%s\n' "$dock" "$item" >>"$ESTADO"
    done
  done
}

reiniciar_plank() {
  command -v plank >/dev/null 2>&1 || return 0
  if pgrep -u "$USER" -x plank >/dev/null 2>&1; then
    killall plank >/dev/null 2>&1 || true
    sleep 0.5
  fi
  nohup plank >/dev/null 2>&1 &
  disown || true
}

if [[ "$(id -u)" -eq 0 ]]; then
  mensaje_error "$(pg err_root_install)"
  exit 1
fi

if [[ ! -f "$ROOT/meson.build" ]]; then
  mensaje_error "$(pg err_no_files)"
  exit 1
fi

if ! command -v apt-get >/dev/null 2>&1; then
  mensaje_error "$(pg err_not_debian)"
  exit 1
fi

if ! preguntar "$(pg ask_start)"; then
  exit 0
fi

mapfile -t FALTAN < <(paquetes_faltantes)
if ((${#FALTAN[@]})); then
  log "Instalando paquetes: ${FALTAN[*]}"
  if [[ "$GUI" -eq 1 ]]; then
    zenity --info --title="$TITULO" --width=420 --text="$(pg missing_tools)" || true
  else
    printf '%b\n' "$(pgf missing_packages "${FALTAN[*]}")"
  fi
  if ! como_admin "$ROOT/install.sh" --instalar-paquetes "${FALTAN[@]}" >>"$LOG" 2>&1; then
    detalle="$(grep -E '^E: ' "$LOG" | tail -3 || true)"
    [[ -n "$detalle" ]] || detalle="$(pg auth_cancelled)"
    mensaje_error "$(pgf err_deps "$detalle" "$LOG")"
    exit 1
  fi
fi

log "Compilando..."
compilar() {
  if [[ ! -d "$ROOT/build" ]]; then
    meson setup --prefix=/usr "$ROOT/build"
  else
    meson setup --reconfigure --prefix=/usr "$ROOT/build"
  fi
  meson compile -C "$ROOT/build"
}

if [[ "$GUI" -eq 1 ]]; then
  if ! (
    echo "5"
    echo "# $(pg preparing)"
    if [[ ! -d "$ROOT/build" ]]; then
      meson setup --prefix=/usr "$ROOT/build" >>"$LOG" 2>&1
    else
      meson setup --reconfigure --prefix=/usr "$ROOT/build" >>"$LOG" 2>&1
    fi
    echo "50"
    echo "# $(pg compiling_step)"
    meson compile -C "$ROOT/build" >>"$LOG" 2>&1
    echo "100"
  ) | zenity --progress --title="$TITULO" --width=420 --auto-close --no-cancel --text="$(pg compiling)"; then
    mensaje_error "$(pgf err_compile "$LOG")"
    exit 1
  fi
else
  compilar
fi

log "Instalando el módulo..."
if [[ "$GUI" -eq 1 ]]; then
  zenity --info --title="$TITULO" --width=420 --text="$(pg copying_module)" || true
fi
if ! como_admin "$ROOT/install.sh" --instalar-modulo "$ROOT" >>"$LOG" 2>&1; then
  mensaje_error "$(pgf err_install "$LOG")"
  exit 1
fi

LIBDIR="$(pkg-config --variable=libdir plank 2>/dev/null || echo /usr/lib)"
mkdir -p "$(dirname "$ESTADO")"
if [[ ! -f "$ESTADO" ]]; then
  printf 'DOCKLET=%s\n' "$LIBDIR/plank/docklets/libdocklet-app-group.so" >"$ESTADO"
else
  grep -q '^DOCKLET=' "$ESTADO" || printf 'DOCKLET=%s\n' "$LIBDIR/plank/docklets/libdocklet-app-group.so" >>"$ESTADO"
fi

if preguntar "$(pg ask_sample_groups)"; then
  configurar_grupos
  log "Grupos creados en $GRUPOS_DIR"
fi

reiniciar_plank

mensaje "$(pg done_install)"
exit 0
